package com.gushiii.recommend;

import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.EnableAspectJAutoProxy;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication(scanBasePackages = {"com.gushiii.recommend"})
@MapperScan("com.gushiii.recommend.dal")
@EnableAspectJAutoProxy(proxyTargetClass = true)
public class RecommendSysApplication {

    public static void main(String[] args) {
        SpringApplication.run(RecommendSysApplication.class, args);
    }

}
